-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelLogic where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsLogic

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transArgId :: AbsLogic.ArgId -> Result
transArgId x = case x of
  AbsLogic.ArgId string -> failure x

transPredId :: AbsLogic.PredId -> Result
transPredId x = case x of
  AbsLogic.PredId string -> failure x

transVarId :: AbsLogic.VarId -> Result
transVarId x = case x of
  AbsLogic.VarId string -> failure x

transIdent :: AbsLogic.Ident -> Result
transIdent x = case x of
  AbsLogic.Ident string -> failure x

transPIdent :: AbsLogic.PIdent -> Result
transPIdent x = case x of
  AbsLogic.PIdent string -> failure x

transSequent :: AbsLogic.Sequent -> Result
transSequent x = case x of
  AbsLogic.Seq forms form steps -> failure x

transStep :: AbsLogic.Step -> Result
transStep x = case x of
  AbsLogic.StepPrem form -> failure x
  AbsLogic.StepFree var -> failure x
  AbsLogic.StepAssume form -> failure x
  AbsLogic.StepScope steps -> failure x
  AbsLogic.StepForm form args -> failure x

transArg :: AbsLogic.Arg -> Result
transArg x = case x of
  AbsLogic.ArgLit argid -> failure x

transForm :: AbsLogic.Form -> Result
transForm x = case x of
  AbsLogic.FormBot -> failure x
  AbsLogic.FormEq term1 term2 -> failure x
  AbsLogic.FormAll var form -> failure x
  AbsLogic.FormSome var form -> failure x
  AbsLogic.FormNot form -> failure x
  AbsLogic.FormAnd form1 form2 -> failure x
  AbsLogic.FormOr form1 form2 -> failure x
  AbsLogic.FormIf form1 form2 -> failure x
  AbsLogic.FormPred pred -> failure x

transPred :: AbsLogic.Pred -> Result
transPred x = case x of
  AbsLogic.PredN predid terms -> failure x
  AbsLogic.Pred0 predid -> failure x

transVar :: AbsLogic.Var -> Result
transVar x = case x of
  AbsLogic.VarLit varid -> failure x

transFun :: AbsLogic.Fun -> Result
transFun x = case x of
  AbsLogic.FunLit varid terms -> failure x

transTerm :: AbsLogic.Term -> Result
transTerm x = case x of
  AbsLogic.TermVar var -> failure x
  AbsLogic.TermFun fun -> failure x
