-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language logic.

module Logic.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Sequent = Seq [Form] Form [Step]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Step
    = StepPrem Form
    | StepDecConst TermId
    | StepDecVar TermId
    | StepDecFun TermId [TermId]
    | StepAssume Form
    | StepProof [Step]
    | StepForm RuleId [Arg] Form
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Arg = ArgSub Step | ArgLit Integer
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Form
    = FormBot
    | FormEq Term Term
    | FormPred Pred
    | FormAll TermId Form
    | FormSome TermId Form
    | FormNot Form
    | FormAnd Form Form
    | FormOr Form Form
    | FormIf Form Form
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Pred = Pred PredId Params
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Term = Term TermId Params
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Params = Params [Term]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Nil = Nil
  deriving (C.Eq, C.Ord, C.Show, C.Read)

params :: Nil -> Params
params = \ n -> Params []

newtype PredId = PredId String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype TermId = TermId String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

newtype RuleId = RuleId String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

